import crypto from 'node:crypto';
import { getDatabase } from './db.js';
import { getDefaultPrompts } from '../prompts/defaultPrompts.js';
import { normalizePromptInput } from '../prompts/promptFormatter.js';
function parse(value, fallback){ try{return value?JSON.parse(value):fallback;}catch{return fallback;} }
function map(row){ return row?{ id:row.id,title:row.title,description:row.description,category:row.category,tags:parse(row.tags_json,[]),promptText:row.prompt_text,variables:parse(row.variables_json,[]),toolHint:row.tool_hint,version:row.version,isFavorite:Boolean(row.is_favorite),createdAt:row.created_at,updatedAt:row.updated_at}:null; }
export function createPrompt(prompt){ const db=getDatabase(); const next=normalizePromptInput(prompt); const id=next.id??`prompt_${crypto.randomUUID()}`; db.prepare('INSERT INTO prompt_library (id,title,description,category,tags_json,prompt_text,variables_json,tool_hint,is_favorite) VALUES (?,?,?,?,?,?,?,?,?)').run(id,next.title,next.description??'',next.category??'General',JSON.stringify(next.tags),next.promptText,JSON.stringify(next.variables),next.toolHint??'any',next.isFavorite?1:0); return getPromptById(id); }
export function updatePrompt(id, updates){ const current=getPromptById(id); if(!current) return null; const next=normalizePromptInput({...current,...updates}); getDatabase().prepare('UPDATE prompt_library SET title=?,description=?,category=?,tags_json=?,prompt_text=?,variables_json=?,tool_hint=?,is_favorite=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next.title,next.description??'',next.category??'General',JSON.stringify(next.tags),next.promptText,JSON.stringify(next.variables),next.toolHint??'any',next.isFavorite?1:0,id); return getPromptById(id); }
export function deletePrompt(id){ return getDatabase().prepare('DELETE FROM prompt_library WHERE id=?').run(id).changes>0; }
export function duplicatePrompt(id){ const prompt=getPromptById(id); return prompt?createPrompt({...prompt,id:undefined,title:`${prompt.title} Copy`,isFavorite:false}):null; }
export function getPromptById(id){ return map(getDatabase().prepare('SELECT * FROM prompt_library WHERE id=?').get(id)); }
export function listPrompts(filters={}){ let rows=getDatabase().prepare('SELECT * FROM prompt_library ORDER BY is_favorite DESC, updated_at DESC').all().map(map); if(filters.favorite) rows=rows.filter(p=>p.isFavorite); if(filters.category&&filters.category!=='all') rows=rows.filter(p=>p.category===filters.category); if(filters.toolHint&&filters.toolHint!=='all') rows=rows.filter(p=>p.toolHint===filters.toolHint||p.toolHint==='any'); if(filters.search) rows=rows.filter(p=>`${p.title} ${p.description} ${p.category} ${p.tags.join(' ')} ${p.promptText}`.toLowerCase().includes(filters.search.toLowerCase())); return rows; }
export function searchPrompts(query, filters={}){ return listPrompts({...filters,search:query}); }
export function togglePromptFavorite(id){ const prompt=getPromptById(id); if(!prompt) return null; getDatabase().prepare('UPDATE prompt_library SET is_favorite=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(prompt.isFavorite?0:1,id); return getPromptById(id); }
export function seedDefaultPromptsIfEmpty(){ const db=getDatabase(); const count=db.prepare('SELECT COUNT(*) as count FROM prompt_library').get().count; if(count>0) return {seeded:0}; let seeded=0; for(const prompt of getDefaultPrompts()){ createPrompt(prompt); seeded++; } return {seeded}; }
