import crypto from 'node:crypto';
import { getDatabase } from './db.js';
import { getDefaultTemplates } from '../templates/defaultTemplates.js';
function parse(v,f){try{return v?JSON.parse(v):f;}catch{return f;}}
function norm(t){return {...t,tags:Array.isArray(t.tags)?t.tags:String(t.tags??'').split(',').map(x=>x.trim()).filter(Boolean),tools:Array.isArray(t.tools)?t.tools:[]};}
function map(row){return row?{id:row.id,name:row.name,description:row.description,category:row.category,tags:parse(row.tags_json,[]),templateJson:parse(row.template_json,{}),inputSchema:parse(row.input_schema_json,{}),tools:parse(row.tools_json,[]),isBuiltin:Boolean(row.is_builtin),isFavorite:Boolean(row.is_favorite),createdAt:row.created_at,updatedAt:row.updated_at}:null;}
export function createTemplate(template){const t=norm(template); const id=t.id??`template_${crypto.randomUUID()}`; getDatabase().prepare('INSERT INTO workflow_templates (id,name,description,category,tags_json,template_json,input_schema_json,tools_json,is_builtin,is_favorite) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,t.name,t.description??'',t.category??'General',JSON.stringify(t.tags),JSON.stringify(t.templateJson??{}),JSON.stringify(t.inputSchema??{}),JSON.stringify(t.tools),t.isBuiltin?1:0,t.isFavorite?1:0); return getTemplateById(id);}
export function updateTemplate(id,updates){const current=getTemplateById(id); if(!current||current.isBuiltin) return null; const t=norm({...current,...updates}); getDatabase().prepare('UPDATE workflow_templates SET name=?,description=?,category=?,tags_json=?,template_json=?,input_schema_json=?,tools_json=?,is_favorite=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(t.name,t.description??'',t.category??'General',JSON.stringify(t.tags),JSON.stringify(t.templateJson??{}),JSON.stringify(t.inputSchema??{}),JSON.stringify(t.tools),t.isFavorite?1:0,id); return getTemplateById(id);}
export function deleteTemplate(id){const t=getTemplateById(id); if(!t||t.isBuiltin) return false; return getDatabase().prepare('DELETE FROM workflow_templates WHERE id=?').run(id).changes>0;}
export function duplicateTemplate(id){const t=getTemplateById(id); return t?createTemplate({...t,id:undefined,name:`${t.name} Copy`,isBuiltin:false,isFavorite:false}):null;}
export function getTemplateById(id){return map(getDatabase().prepare('SELECT * FROM workflow_templates WHERE id=?').get(id));}
export function listTemplates(filters={}){let rows=getDatabase().prepare('SELECT * FROM workflow_templates ORDER BY is_builtin DESC,is_favorite DESC,updated_at DESC').all().map(map); if(filters.favorite) rows=rows.filter(t=>t.isFavorite); if(filters.category&&filters.category!=='all') rows=rows.filter(t=>t.category===filters.category); if(filters.search) rows=rows.filter(t=>`${t.name} ${t.description} ${t.category} ${t.tags.join(' ')}`.toLowerCase().includes(filters.search.toLowerCase())); return rows;}
export function searchTemplates(query,filters={}){return listTemplates({...filters,search:query});}
export function toggleTemplateFavorite(id){const t=getTemplateById(id); if(!t) return null; getDatabase().prepare('UPDATE workflow_templates SET is_favorite=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(t.isFavorite?0:1,id); return getTemplateById(id);}
export function seedDefaultTemplatesIfEmpty(){const db=getDatabase(); const count=db.prepare('SELECT COUNT(*) as count FROM workflow_templates').get().count; if(count>0) return {seeded:0}; let seeded=0; for(const t of getDefaultTemplates()){createTemplate(t); seeded++;} return {seeded};}
