import crypto from 'node:crypto';
import { getDatabase } from './db.js';
import { isValidVariableName, SYSTEM_VARIABLE_NAMES } from '../shared/validation.js';
function parse(v,f){try{return v?JSON.parse(v):f;}catch{return f;}}
function mapVar(row){return row?{id:row.id,name:row.name,label:row.label,description:row.description,value:row.is_secret?'••••••':row.value,type:row.type,scope:row.scope,isSecret:Boolean(row.is_secret),createdAt:row.created_at,updatedAt:row.updated_at}:null;}
function mapPreset(row){return row?{id:row.id,workflowId:row.workflow_id,templateId:row.template_id,name:row.name,values:parse(row.values_json,{}),createdAt:row.created_at,updatedAt:row.updated_at}:null;}
function assertName(name){ if(!isValidVariableName(name)) throw new Error('Variable names may only contain letters, numbers, and underscores and cannot start with a number.'); if(SYSTEM_VARIABLE_NAMES.has(name)) throw new Error(`Variable "${name}" conflicts with a reserved system variable.`); }
export function createVariable(variable){assertName(variable.name); const id=variable.id??`var_${crypto.randomUUID()}`; getDatabase().prepare('INSERT INTO reusable_variables (id,name,label,description,value,type,scope,is_secret) VALUES (?,?,?,?,?,?,?,?)').run(id,variable.name,variable.label??variable.name,variable.description??'',variable.value??'',variable.type??'text',variable.scope??'global',variable.isSecret?1:0); return getVariableById(id);}
export function updateVariable(id,updates){const current=getVariableById(id); if(!current) return null; const next={...current,...updates}; assertName(next.name); getDatabase().prepare('UPDATE reusable_variables SET name=?,label=?,description=?,value=?,type=?,scope=?,is_secret=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next.name,next.label??next.name,next.description??'',updates.value??current.value,next.type??'text',next.scope??'global',next.isSecret?1:0,id); return getVariableById(id);}
export function deleteVariable(id){return getDatabase().prepare('DELETE FROM reusable_variables WHERE id=?').run(id).changes>0;}
export function getVariableById(id){return mapVar(getDatabase().prepare('SELECT * FROM reusable_variables WHERE id=?').get(id));}
export function listVariables(filters={}){let rows=getDatabase().prepare('SELECT * FROM reusable_variables ORDER BY scope,name').all().map(mapVar); if(filters.scope&&filters.scope!=='all') rows=rows.filter(v=>v.scope===filters.scope); if(filters.type&&filters.type!=='all') rows=rows.filter(v=>v.type===filters.type); if(filters.search) rows=rows.filter(v=>`${v.name} ${v.label} ${v.description}`.toLowerCase().includes(filters.search.toLowerCase())); return rows;}
export function getVariableContext(scope='global'){const rows=getDatabase().prepare('SELECT * FROM reusable_variables WHERE is_secret=0 AND (scope=? OR scope="global")').all(scope); return Object.fromEntries(rows.map(row=>[row.name,row.value]));}
export function createInputPreset(preset){const id=preset.id??`preset_${crypto.randomUUID()}`; getDatabase().prepare('INSERT INTO workflow_input_presets (id,workflow_id,template_id,name,values_json) VALUES (?,?,?,?,?)').run(id,preset.workflowId??null,preset.templateId??null,preset.name,JSON.stringify(preset.values??{})); return getInputPresetById(id);}
export function updateInputPreset(id,updates){const current=getInputPresetById(id); if(!current) return null; const next={...current,...updates}; getDatabase().prepare('UPDATE workflow_input_presets SET workflow_id=?,template_id=?,name=?,values_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(next.workflowId??null,next.templateId??null,next.name,JSON.stringify(next.values??{}),id); return getInputPresetById(id);}
export function deleteInputPreset(id){return getDatabase().prepare('DELETE FROM workflow_input_presets WHERE id=?').run(id).changes>0;}
export function listInputPresets(filters={}){let rows=getDatabase().prepare('SELECT * FROM workflow_input_presets ORDER BY updated_at DESC').all().map(mapPreset); if(filters.workflowId) rows=rows.filter(p=>p.workflowId===filters.workflowId); if(filters.templateId) rows=rows.filter(p=>p.templateId===filters.templateId); return rows;}
export function getInputPresetById(id){return mapPreset(getDatabase().prepare('SELECT * FROM workflow_input_presets WHERE id=?').get(id));}
