import { contextBridge, ipcRenderer } from 'electron';

const unwrap = async (promise) => {
  const response = await promise;
  if (response && typeof response === 'object' && 'ok' in response) {
    if (!response.ok) throw new Error(response.error);
    return response.data;
  }
  return response;
};

const appAPI = {
  getAppInfo: () => ipcRenderer.invoke('settings:get-app-info'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => unwrap(ipcRenderer.invoke('settings:save', settings)),
  validateWorkflow: (workflow) => unwrap(ipcRenderer.invoke('workflow:validate', workflow)),
  runWorkflow: (workflow) => unwrap(ipcRenderer.invoke('workflow:run', workflow)),
  retryPausedStep: (runId) => unwrap(ipcRenderer.invoke('workflow:retry-paused-step', runId)),
  resumeWorkflow: (runId) => unwrap(ipcRenderer.invoke('workflow:resume', runId)),
  getRunState: (runId) => unwrap(ipcRenderer.invoke('workflow:get-run-state', runId)),
  enqueueWorkflowRun: (workflow) => unwrap(ipcRenderer.invoke('workflow:enqueue-run', workflow)),
  getRunQueueStatus: () => unwrap(ipcRenderer.invoke('workflow:queue-status')),
  cancelQueuedRun: (runId) => unwrap(ipcRenderer.invoke('workflow:cancel-queued-run', runId)),
  clearCompletedQueueItems: () => unwrap(ipcRenderer.invoke('workflow:clear-completed-queue-items')),
  listWorkflows: () => unwrap(ipcRenderer.invoke('workflow:list')),
  getWorkflow: (workflowId) => unwrap(ipcRenderer.invoke('workflow:get', workflowId)),
  importWorkflow: (workflow) => unwrap(ipcRenderer.invoke('workflow:import', workflow)),
  duplicateWorkflow: (workflowId) => unwrap(ipcRenderer.invoke('workflow:duplicate', workflowId)),
  deleteWorkflow: (workflowId) => unwrap(ipcRenderer.invoke('workflow:delete', workflowId)),
  listRuns: () => unwrap(ipcRenderer.invoke('runs:list')),
  getRun: (runId) => unwrap(ipcRenderer.invoke('runs:get', runId)),
  listResults: () => unwrap(ipcRenderer.invoke('results:list')),
  launchBrowser: () => unwrap(ipcRenderer.invoke('browser:launch')),
  closeBrowser: () => unwrap(ipcRenderer.invoke('browser:close')),
  getBrowserStatus: () => unwrap(ipcRenderer.invoke('browser:status')),
  openUrl: (url) => unwrap(ipcRenderer.invoke('browser:open-url', url)),
  openTool: (toolName) => unwrap(ipcRenderer.invoke('browser:open-tool', toolName)),
  listBrowserTabs: () => unwrap(ipcRenderer.invoke('browser:list-tabs')),
  closeBrowserTab: (urlPart) => unwrap(ipcRenderer.invoke('browser:close-tab', urlPart)),
  bringBrowserTabToFront: (urlPart) => unwrap(ipcRenderer.invoke('browser:bring-tab-front', urlPart)),
  getBrowserProfileInfo: () => unwrap(ipcRenderer.invoke('browser:profile-info')),
  clearBrowserProfile: () => unwrap(ipcRenderer.invoke('browser:clear-profile')),
  listConnectors: () => unwrap(ipcRenderer.invoke('connectors:list')),
  exportRunAsMarkdown: (runId) => ipcRenderer.invoke('export:run-markdown', runId),
  exportRunAsTxt: (runId) => ipcRenderer.invoke('export:run-txt', runId),
  exportRunAsJson: (runId) => ipcRenderer.invoke('export:run-json', runId),
  exportRunAsZip: (runId) => ipcRenderer.invoke('export:run-zip', runId),
  openPath: (filePath) => ipcRenderer.invoke('files:open-path', filePath),
  openFolder: (folderPath) => ipcRenderer.invoke('files:open-folder', folderPath),
  showInFolder: (filePath) => ipcRenderer.invoke('files:show-in-folder', filePath),
  getProjectPath: (folderName) => ipcRenderer.invoke('files:project-path', folderName),
  listLogs: (filters) => unwrap(ipcRenderer.invoke('logs:list', filters)),
  clearLogs: () => unwrap(ipcRenderer.invoke('logs:clear')),

  listPrompts: (filters) => unwrap(ipcRenderer.invoke('prompts:list', filters)),
  createPrompt: (prompt) => unwrap(ipcRenderer.invoke('prompts:create', prompt)),
  updatePrompt: (id, updates) => unwrap(ipcRenderer.invoke('prompts:update', id, updates)),
  deletePrompt: (id) => unwrap(ipcRenderer.invoke('prompts:delete', id)),
  duplicatePrompt: (id) => unwrap(ipcRenderer.invoke('prompts:duplicate', id)),
  togglePromptFavorite: (id) => unwrap(ipcRenderer.invoke('prompts:toggle-favorite', id)),
  seedDefaultPrompts: () => unwrap(ipcRenderer.invoke('prompts:seed-defaults')),
  listTemplates: (filters) => unwrap(ipcRenderer.invoke('templates:list', filters)),
  createTemplate: (template) => unwrap(ipcRenderer.invoke('templates:create', template)),
  updateTemplate: (id, updates) => unwrap(ipcRenderer.invoke('templates:update', id, updates)),
  deleteTemplate: (id) => unwrap(ipcRenderer.invoke('templates:delete', id)),
  duplicateTemplate: (id) => unwrap(ipcRenderer.invoke('templates:duplicate', id)),
  toggleTemplateFavorite: (id) => unwrap(ipcRenderer.invoke('templates:toggle-favorite', id)),
  seedDefaultTemplates: () => unwrap(ipcRenderer.invoke('templates:seed-defaults')),
  createWorkflowFromTemplate: (templateId, inputValues, options) => unwrap(ipcRenderer.invoke('templates:create-workflow', templateId, inputValues, options)),
  listVariables: (filters) => unwrap(ipcRenderer.invoke('variables:list', filters)),
  createVariable: (variable) => unwrap(ipcRenderer.invoke('variables:create', variable)),
  updateVariable: (id, updates) => unwrap(ipcRenderer.invoke('variables:update', id, updates)),
  deleteVariable: (id) => unwrap(ipcRenderer.invoke('variables:delete', id)),
  previewVariableResolution: (text, context) => unwrap(ipcRenderer.invoke('variables:preview-resolution', text, context)),
  listInputPresets: (filters) => unwrap(ipcRenderer.invoke('input-presets:list', filters)),
  createInputPreset: (preset) => unwrap(ipcRenderer.invoke('input-presets:create', preset)),
  updateInputPreset: (id, updates) => unwrap(ipcRenderer.invoke('input-presets:update', id, updates)),
  deleteInputPreset: (id) => unwrap(ipcRenderer.invoke('input-presets:delete', id)),

  loadSettings: () => unwrap(ipcRenderer.invoke('settings:load')),
  resetSettings: () => unwrap(ipcRenderer.invoke('settings:reset')),
  resetSettingsSection: (sectionName) => unwrap(ipcRenderer.invoke('settings:reset-section', sectionName)),
  exportSettings: () => unwrap(ipcRenderer.invoke('settings:export')),
  importSettings: (settingsJson) => unwrap(ipcRenderer.invoke('settings:import', settingsJson)),
  createDatabaseBackup: () => unwrap(ipcRenderer.invoke('backup:create-database')),
  createFullBackup: (options) => unwrap(ipcRenderer.invoke('backup:create-full', options)),
  listBackups: (filters) => unwrap(ipcRenderer.invoke('backup:list', filters)),
  validateBackup: (backupPath) => unwrap(ipcRenderer.invoke('backup:validate', backupPath)),
  restoreBackup: (backupPath, options) => unwrap(ipcRenderer.invoke('backup:restore', backupPath, options)),
  deleteBackup: (backupPath) => unwrap(ipcRenderer.invoke('backup:delete', backupPath)),
  exportWorkflowPackage: (workflowId, options) => unwrap(ipcRenderer.invoke('package:export-workflow', workflowId, options)),
  exportWorkflowJsonOnly: (workflowId, options) => unwrap(ipcRenderer.invoke('package:export-workflow-json', workflowId, options)),
  validateWorkflowPackage: (packagePath) => unwrap(ipcRenderer.invoke('package:validate-import', packagePath)),
  importWorkflowPackage: (packagePath, options) => unwrap(ipcRenderer.invoke('package:import-workflow', packagePath, options)),
  runQuickHealthCheck: () => unwrap(ipcRenderer.invoke('health:quick-check')),
  runDeepHealthCheck: () => unwrap(ipcRenderer.invoke('health:deep-check')),
  checkDataIntegrity: () => unwrap(ipcRenderer.invoke('health:integrity-check')),
  repairHealthIssues: (options) => unwrap(ipcRenderer.invoke('health:repair', options)),
  exportDiagnostics: (options) => unwrap(ipcRenderer.invoke('diagnostics:export', options)),
  getDatabaseStats: () => unwrap(ipcRenderer.invoke('maintenance:db-stats')),
  vacuumDatabase: () => unwrap(ipcRenderer.invoke('maintenance:vacuum')),
  clearOldLogs: (days) => unwrap(ipcRenderer.invoke('maintenance:clear-old-logs', days)),

  checkConnectorReadiness: (toolName, options) => unwrap(ipcRenderer.invoke('readiness:check-connector', toolName, options)),
  checkAllConnectorReadiness: (options) => unwrap(ipcRenderer.invoke('readiness:check-all-connectors', options)),
  getConnectorReadinessSummary: () => unwrap(ipcRenderer.invoke('readiness:summary')),
  runWorkflowPreflightChecks: (workflow) => unwrap(ipcRenderer.invoke('preflight:workflow', workflow)),
  getOnboardingState: () => unwrap(ipcRenderer.invoke('onboarding:get')),
  updateOnboardingState: (updates) => unwrap(ipcRenderer.invoke('onboarding:update', updates)),
  markOnboardingStepComplete: (stepId) => unwrap(ipcRenderer.invoke('onboarding:complete-step', stepId)),
  resetOnboarding: () => unwrap(ipcRenderer.invoke('onboarding:reset')),
  completeOnboarding: () => unwrap(ipcRenderer.invoke('onboarding:complete')),
  listShortcuts: () => unwrap(ipcRenderer.invoke('shortcuts:list')),
  getShortcutSettings: () => unwrap(ipcRenderer.invoke('shortcuts:get-settings')),
  updateShortcutSettings: (settings) => unwrap(ipcRenderer.invoke('shortcuts:update-settings', settings)),
  getVersionInfo: () => unwrap(ipcRenderer.invoke('app:version-info')),
  getBuildInfo: () => unwrap(ipcRenderer.invoke('app:build-info')),
  openUserGuide: () => unwrap(ipcRenderer.invoke('app:open-user-guide')),
  openTroubleshooting: () => unwrap(ipcRenderer.invoke('app:open-troubleshooting'))
};

contextBridge.exposeInMainWorld('appAPI', appAPI);
contextBridge.exposeInMainWorld('aiWorkflowRunner', appAPI);
