import { getBrowserStatus, launchBrowser } from '../browser/browserManager.js';
import { openToolTab, openUrlTab } from '../browser/tabManager.js';
import { chatgptConnector } from '../connectors/chatgpt.connector.js';
import { geminiConnector } from '../connectors/gemini.connector.js';
import { getConnector, listConnectors } from '../connectors/connectorRegistry.js';
let lastSummary = null;
function base(tool,label){return {tool,label,ready:false,status:'not_ready',checks:[],warnings:[],errors:[],actions:[],checkedAt:new Date().toISOString()};}
function check(id,label,status,message){return {id,label,status,message};}
async function checkBrowser(result){const status=await getBrowserStatus(); result.checks.push(check('browser','Browser running',status.running?'ok':'warning',status.running?'Persistent browser is running.':'Browser is not running; it can be launched from Browser Panel.')); if(!status.running) result.warnings.push('Browser is not running.'); return status.running;}
export async function checkConnectorReadiness(toolName, options={}){ const connector=getConnector(toolName); const label=connector?.label??toolName; const result=base(toolName,label); if(toolName==='mock'){result.ready=true; result.status='ready'; result.checks.push(check('mock','Mock runner','ok','Mock runner is available.')); return result;} if(!connector?.implemented){result.status='not_implemented'; result.errors.push(`${label} is not implemented yet.`); result.actions.push('view_troubleshooting'); return result;} if(toolName==='generic'){ if(options.url){await launchBrowser(); const tab=await openUrlTab(options.url,{reuse:true}); result.checks.push(check('url','Generic URL','ok',`Opened ${tab.url}`)); result.ready=true; result.status='ready';} else {result.warnings.push('Generic URL is required for a full readiness check.'); result.checks.push(check('url','Generic URL','warning','Provide a URL and selectors for a full check.')); result.status='manual_action_required';} return result;} await launchBrowser(); const pageInfo=await openToolTab(toolName,{includePage:true}); result.checks.push(check('tab',`${label} tab`,'ok',`Opened ${pageInfo.url}`)); const ready = toolName==='chatgpt' ? await chatgptConnector.isReady(pageInfo.page) : await geminiConnector.isReady(pageInfo.page); result.checks.push(check('prompt','Prompt input',ready.ready?'ok':'warning',ready.reason ?? 'Prompt input is visible.')); if(ready.ready){result.ready=true; result.status='ready';} else {result.status='manual_action_required'; result.warnings.push(`${label} may require manual login.`); result.actions.push(`open_${toolName}`);} return result; }
export async function checkAllConnectorReadiness(options={}){ const tools=['mock','chatgpt','gemini','generic','claude','perplexity']; const results=[]; for(const tool of tools){try{results.push(await checkConnectorReadiness(tool,options));}catch(error){const r=base(tool,tool); r.status='error'; r.errors.push(error.message); results.push(r);}} lastSummary={checkedAt:new Date().toISOString(),results,connectors:results,readyCount:results.filter(r=>r.ready).length,total:results.length}; return lastSummary;}
export async function getConnectorReadinessSummary(){return lastSummary ?? {checkedAt:null,connectors:listConnectors().map(c=>({tool:c.name,label:c.label,ready:c.name==='mock',implemented:c.implemented,status:c.name==='mock'?'ready':c.implemented?'unknown':'not_implemented'}))};}
