import fs from 'node:fs/promises';
import path from 'node:path';
import { getWorkflowById } from '../storage/workflows.js';
import { listPrompts } from '../storage/prompts.js';
import { listVariables, listInputPresets } from '../storage/variables.js';
import { ensureDir, projectPath, safeName } from '../shared/fileUtils.js';
import { createPackageManifest } from './packageManifest.js';
export async function exportWorkflowPackage(workflowId, options={}){const workflow=getWorkflowById(workflowId); if(!workflow) throw new Error('Workflow not found.'); const manifest=createPackageManifest({workflowName:workflow.name, included:{prompts:options.includePrompts!==false,variables:options.includeVariables!==false,inputPresets:options.includePresets!==false,templates:Boolean(options.includeTemplateSource)}, requirements:{tools:[...new Set((workflow.definition?.steps??[]).map(s=>s.tool).filter(Boolean))], supportsParallel:JSON.stringify(workflow.definition).includes('"parallel"')}}); const payload={manifest,workflow:workflow.definition,prompts:options.includePrompts===false?[]:listPrompts(),variables:options.includeVariables===false?[]:listVariables().filter(v=>!v.isSecret||options.includeSecretValues),inputPresets:options.includePresets===false?[]:listInputPresets({}),readme:'Browser-based tools require manual login in the persistent browser profile.'}; const dir=await ensureDir(projectPath('exports','workflow-packages')); const filePath=path.join(dir,`${safeName(workflow.name)}-${workflowId}.aiworkflowpkg`); await fs.writeFile(filePath,JSON.stringify(payload,null,2),'utf8'); return filePath;}
export async function exportWorkflowJsonOnly(workflowId){const workflow=getWorkflowById(workflowId); if(!workflow) throw new Error('Workflow not found.'); const dir=await ensureDir(projectPath('exports','workflow-packages')); const filePath=path.join(dir,`${safeName(workflow.name)}-${workflowId}.json`); await fs.writeFile(filePath,JSON.stringify(workflow.definition,null,2),'utf8'); return filePath;}
