const baseInput = (label, extra = {}) => ({ type: 'text', label, required: true, default: '', ...extra });
export const defaultTemplates = [
  { id:'youtube_full_package', name:'YouTube Full Package', description:'Research, script, parallel assets, and final package.', category:'YouTube', tags:['youtube','parallel'], tools:['chatgpt','gemini'], isBuiltin:true, inputSchema:{ topic:baseInput('Topic'), targetAudience:baseInput('Target Audience',{default:'students'}), videoLength:baseInput('Video Length',{default:'8 minutes'}), tone:{type:'select',label:'Tone',required:true,default:'simple',options:['simple','professional','friendly','deep','motivational']} }, templateJson:{ workflowName:'YouTube Full Package - {{topic}}', description:'Template workflow for a complete YouTube package.', inputs:{topic:'',targetAudience:'students',videoLength:'8 minutes',tone:'simple'}, settings:{maxConcurrency:2}, steps:[{id:'research',tool:'chatgpt',mode:'single',prompt:'Research {{topic}} for {{targetAudience}}.',saveAs:'research_output'},{id:'script',tool:'chatgpt',mode:'single',prompt:'Write a {{videoLength}} script in a {{tone}} tone using:\n\n{{research_output}}',saveAs:'script_output'},{id:'assets',mode:'parallel',label:'Assets',steps:[{id:'titles',tool:'gemini',mode:'single',prompt:'Create titles for:\n\n{{script_output}}',saveAs:'titles_output'},{id:'thumbnails',tool:'chatgpt',mode:'single',prompt:'Create thumbnail prompts for:\n\n{{script_output}}',saveAs:'thumbnail_output'}]},{id:'final',tool:'chatgpt',mode:'single',prompt:'Create final package with {{script_output}} {{titles_output}} {{thumbnail_output}}',saveAs:'final_output'}] } },
  { id:'study_content_pack', name:'Study Content Pack', description:'Explanation, notes, quiz, examples, and final pack.', category:'Education', tags:['study'], tools:['mock','chatgpt','gemini'], isBuiltin:true, inputSchema:{ topic:baseInput('Topic'), classLevel:baseInput('Class Level',{default:'Class 8'}), language:baseInput('Language',{default:'English'}), difficulty:{type:'select',label:'Difficulty',required:true,default:'easy',options:['easy','medium','hard']} }, templateJson:{ workflowName:'Study Pack - {{topic}}', inputs:{topic:'',classLevel:'Class 8',language:'English',difficulty:'easy'}, steps:[{id:'explanation',tool:'mock',mode:'single',prompt:'Explain {{topic}} for {{classLevel}} in {{language}}.',saveAs:'explanation'},{id:'quiz',tool:'mock',mode:'single',prompt:'Create a {{difficulty}} quiz from {{explanation}}',saveAs:'quiz'},{id:'final_pack',tool:'mock',mode:'single',prompt:'Combine {{explanation}} and {{quiz}}',saveAs:'final_pack'}] } },
  { id:'code_fix_workflow', name:'Code Fix Workflow', description:'Analyze a bug and produce a fix explanation.', category:'Coding', tags:['code'], tools:['chatgpt'], isBuiltin:true, inputSchema:{ code:{type:'textarea',label:'Code',required:true,default:''}, bugDescription:baseInput('Bug Description'), expectedBehavior:baseInput('Expected Behavior') }, templateJson:{ workflowName:'Code Fix - {{bugDescription}}', inputs:{code:'',bugDescription:'',expectedBehavior:''}, steps:[{id:'analyze_bug',tool:'mock',mode:'single',prompt:'Analyze bug: {{bugDescription}}\nExpected: {{expectedBehavior}}\nCode:\n{{code}}',saveAs:'analysis'},{id:'suggest_fix',tool:'mock',mode:'single',prompt:'Suggest a fix from:\n\n{{analysis}}',saveAs:'fix'}] } },
  { id:'research_summary', name:'Research Summary Workflow', description:'Research and summarize a topic.', category:'Research', tags:['summary'], tools:['mock','chatgpt'], isBuiltin:true, inputSchema:{ topic:baseInput('Topic'), depth:{type:'select',label:'Depth',required:true,default:'medium',options:['quick','medium','deep']}, outputStyle:baseInput('Output Style',{default:'bullet points'}) }, templateJson:{ workflowName:'Research Summary - {{topic}}', inputs:{topic:'',depth:'medium',outputStyle:'bullet points'}, steps:[{id:'research',tool:'mock',mode:'single',prompt:'Do {{depth}} research on {{topic}}',saveAs:'research_output'},{id:'summary',tool:'mock',mode:'single',prompt:'Summarize as {{outputStyle}}:\n\n{{research_output}}',saveAs:'summary_output'}] } },
  { id:'product_content', name:'Product Content Workflow', description:'Create product copy and captions.', category:'Marketing', tags:['product','marketing'], tools:['mock','chatgpt'], isBuiltin:true, inputSchema:{ productName:baseInput('Product Name'), targetCustomer:baseInput('Target Customer'), platform:baseInput('Platform',{default:'Instagram'}) }, templateJson:{ workflowName:'Product Content - {{productName}}', inputs:{productName:'',targetCustomer:'',platform:'Instagram'}, steps:[{id:'benefits',tool:'mock',mode:'single',prompt:'List benefits of {{productName}} for {{targetCustomer}}',saveAs:'benefits_output'},{id:'copy',tool:'mock',mode:'single',prompt:'Write {{platform}} copy using:\n\n{{benefits_output}}',saveAs:'copy_output'}] } }
];
export function getDefaultTemplates(){ return defaultTemplates; }
